parameters:
    dos.settings.resolver.abstract.class: DoS\SettingsBundle\Resolver\AbstractResolver
    dos.settings.schema.general.class: DoS\SettingsBundle\Schema\GeneralSettingsSchema
    dos.settings.controller.class: DoS\SettingsBundle\Controller\SettingsController

services:
    dos.settings.resolver.abstract:
        class: %dos.settings.resolver.abstract.class%
        abstract: true
        arguments:
            - @dos.settings

    dos.settings.schema.general:
        class: %dos.settings.schema.general.class%
        arguments:
            - {currency: %dos.core.currency%, locale: %dos.core.locale%}
        tags:
            - {name: dos.settings_schema, namespace: general}

    dos.controller.settings:
        parent: sylius.controller.settings
        class: %dos.settings.controller.class%

    dos.settings:
        alias: sylius.templating.helper.settings
