parameters:
    dos.settings.schema.general.class: DoS\SettingsBundle\Schema\GeneralSettingsSchema

services:

    dos.settings.schema.general:
        class: %dos.settings.schema.general.class%
        arguments:
            - {currency: %currency%, locale: %locale%}
        tags:
            - {name: dos.settings_schema, namespace: general}

    dos.settings:
        alias: sylius.templating.helper.settings
