route_backend_setting_general:
    path: /general
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: general
        template: ui:backend/Settings:general.html.twig
        _sylius:
            redirect: route_backend_setting_general
